// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfmerqcA8hU2SM9ezQkEvM7gSwby3pWDo',
    appId: '1:109614126285:web:f0642d47a42b3b2d6d8584',
    messagingSenderId: '109614126285',
    projectId: 'cloud-firestore-project-74e97',
    authDomain: 'cloud-firestore-project-74e97.firebaseapp.com',
    storageBucket: 'cloud-firestore-project-74e97.appspot.com',
    measurementId: 'G-P72HWGP556',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh0zEh6UMWMs7OtsE6IOZQN7WANBNi894',
    appId: '1:109614126285:android:57c9967cbd55bad16d8584',
    messagingSenderId: '109614126285',
    projectId: 'cloud-firestore-project-74e97',
    storageBucket: 'cloud-firestore-project-74e97.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZviA4bHYf5V4AGvgLejK-_5PZrN3f27g',
    appId: '1:109614126285:ios:4a8add02503833aa6d8584',
    messagingSenderId: '109614126285',
    projectId: 'cloud-firestore-project-74e97',
    storageBucket: 'cloud-firestore-project-74e97.appspot.com',
    iosBundleId: 'com.example.cloudFirestoreApplication',
  );
}
